package com.feiyu.dbconnector.security;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.nio.file.Path;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

class AesCredentialCipherTest {

    private AesCredentialCipher cipher(String key, Path tempDir) {
        CryptoKeyProvider provider = new CryptoKeyProvider(tempDir.toString());
        return new AesCredentialCipher(provider, key != null ? key : "");
    }

    private AesCredentialCipher cipher(String key) {
        return cipher(key, Path.of(System.getProperty("java.io.tmpdir"), "dbconnector-crypto-test"));
    }

    @Test
    void roundTrip(@TempDir Path tempDir) {
        AesCredentialCipher c = cipher("test-key", tempDir);
        String ct = c.encrypt("SYSDBA001");
        assertTrue(ct.startsWith("v1:"));
        assertNotEquals("SYSDBA001", ct);
        assertEquals("SYSDBA001", c.decrypt(ct));
    }

    @Test
    void tamperedCiphertextFails(@TempDir Path tempDir) {
        AesCredentialCipher c = cipher("test-key", tempDir);
        String ct = c.encrypt("SYSDBA001");
        String tampered = ct.substring(0, ct.length() - 2) + "A=";
        assertThrows(IllegalStateException.class, () -> c.decrypt(tampered));
    }

    @Test
    void wrongKeyFails(@TempDir Path tempDir) {
        String ct = cipher("key-one", tempDir).encrypt("SYSDBA001");
        assertThrows(IllegalStateException.class, () -> cipher("key-two", tempDir).decrypt(ct));
    }

    @Test
    void legacyPlaintextPassesThrough(@TempDir Path tempDir) {
        assertEquals("plain", cipher("test-key", tempDir).decrypt("plain"));
    }

    @Test
    void autoGeneratedKeyPersists(@TempDir Path tempDir) {
        AesCredentialCipher c1 = cipher(null, tempDir);
        String ct = c1.encrypt("secret");
        AesCredentialCipher c2 = cipher(null, tempDir);
        assertEquals("secret", c2.decrypt(ct));
    }
}